### ISSUE TITLE
Patch node shader error with intel gpus

### ISSUE THREAD

**Issue by RonYanDaik** [santaclose/noose#1]
Downloaded build.
Started app. And there is no Output node. Also missing in menu so cant add it.

In the console some errors:
```
Failed to compile fragment shader:
WARNING: 0:2: '' :  #version directive missing
WARNING: 0:2: 'patch' : symbol not available in current GLSL version
ERROR: 0:2: 'patch' : syntax error syntax error


[Node provider] Failed to load patch shader
[Node system] Initializing
```

![image](https://user-images.githubusercontent.com/3350340/131636961-97f8c39d-f82a-4149-ae16-dfdf5c83d468.png)

**Comment by santaclose** [comment]
Hey! thank you for trying it out. There is no output node. What you do is select nodes, and that way you can see all of its outputs in the viewport window.

I'm aware of the console error, it happens with Intel GPUs as far as I can tell. I haven't figured out why the error shows up though.

**Comment by RonYanDaik** [comment]
No problem. This app has potential, i was looking for this kind of app for a long time. There are much non-destructible node image editors.

**Comment by santaclose** [comment]
the issue seems to be gone after changing the uniform name
