### ISSUE TITLE
Consumes to much CPU.

### ISSUE THREAD

**Issue by RonYanDaik** [santaclose/noose#2]
Uses up to 15% of CPU even when idle or hidden. For my old slow laptop that's too much. (Blender uses 0.2% cpu when idle)

**Comment by santaclose** [comment]
Yes! I'm pretty sure it's because of the main loop. As far as I know there is no way to make sfml wait for input in there so it ends up executing all the time. I was thinking I could switch to glfw or maybe modify sfml so that it can wait for inputs.

**Comment by santaclose** [comment]
added a function to sfml to sleep the thread while the user is not interacting with the app
